#!/usr/bin/env bash
# assemble.sh — composes the final MP4.
#
# Requires (place in video-build/):
#   - voiceover-raw.wav       (your recorded voice, any sample rate)
#   - screen-capture.mp4      (OBS recording, 1920x1080, 30fps, full take)
#   - phone-sms.mp4           (phone screen recording, vertical 1080x1920 OK)
#   - slides/slide-1.png      (generated by build_captions.py)
#   - slides/slide-2.png
#   - slides/slide-3.png
#   - captions.ass            (generated by build_captions.py)
#
# Output: video-build/custodian-final.mp4 (no captions burned in)
#         video-build/custodian-final-burned.mp4 (captions burned in)
#
# Timing: the screen recording must contain the phone-SMS cut at 0:40-0:45
#         already spliced in (you do that in the OBS recording). The phone-sms.mp4
#         file is used as an OPTIONAL overlay replacement if you recorded phone
#         separately and want to splice it in here instead.

set -euo pipefail

cd "$(dirname "$0")"

VOICE=${1:-voiceover-raw.wav}
SCREEN=${2:-screen-capture.mp4}
PHONE=${3:-phone-sms.mp4}
OUT=${4:-custodian-final.mp4}

[ -f "$VOICE"  ] || { echo "missing $VOICE";  exit 1; }
[ -f "$SCREEN" ] || { echo "missing $SCREEN"; exit 1; }

# Step 1: normalize the screen recording (force 1920x1080 30fps, h264)
echo "[1/5] normalizing screen recording to 1920x1080 30fps h264..."
ffmpeg -y -i "$SCREEN" \
  -vf "scale=1920:1080:force_original_aspect_ratio=decrease,pad=1920:1080:(ow-iw)/2:(oh-ih)/2:black,fps=30" \
  -c:v libx264 -preset fast -crf 18 -pix_fmt yuv420p \
  -an screen-norm.mp4

# Step 2: trim the normalized screen capture to 1:52 (close starts at 1:52)
echo "[2/5] trimming screen recording to 1:52..."
ffmpeg -y -i screen-norm.mp4 -t 112 -c:v copy screen-trim.mp4

# Step 3: build the close segment from the 3 slides
echo "[3/5] building close segment from slides..."
ffmpeg -y \
  -loop 1 -t 3.5 -i slides/slide-1.png \
  -loop 1 -t 3.5 -i slides/slide-2.png \
  -loop 1 -t 3.5 -i slides/slide-3.png \
  -f lavfi -i "color=c=black:s=1920x1080:d=0.5" \
  -filter_complex "[0:v][1:v][2:v][3:v]concat=n=4:v=1[v]" \
  -map "[v]" -c:v libx264 -preset fast -crf 18 -pix_fmt yuv420p close.mp4

# Step 4: stitch screen + close, lay voice on top, sync to 123s total
echo "[4/5] combining screen + close + voiceover..."
ffmpeg -y \
  -i screen-trim.mp4 \
  -i close.mp4 \
  -i "$VOICE" \
  -filter_complex "[0:v][0:a][1:v]concat=n=2:v=1:a=1[outv][outa]" \
  -map "[outv]" -map "[outa]" \
  -c:v libx264 -preset fast -crf 18 -pix_fmt yuv420p \
  -c:a aac -b:a 192k \
  -movflags +faststart \
  "$OUT"

# Step 5 (optional): burn in captions using libass
echo "[5/5] burning in captions..."
if [ -f captions.ass ]; then
  ffmpeg -y -i "$OUT" \
    -vf "subtitles=captions.ass" \
    -c:v libx264 -preset fast -crf 18 -pix_fmt yuv420p \
    -c:a copy \
  "${OUT%.mp4}-burned.mp4"
  echo ""
  echo "============================================================"
  echo "DONE. Outputs:"
  echo "  $OUT          (no captions, captions live in captions.ass)"
  echo "  ${OUT%.mp4}-burned.mp4  (captions burned in)"
  echo "============================================================"
else
  echo "captions.ass not found — skipping burn-in step"
  echo ""
  echo "============================================================"
  echo "DONE. Output: $OUT"
  echo "============================================================"
fi
ffprobe "$OUT" 2>&1 | grep -E "(Duration|Stream)" | head -5
