"""Generate the dependency-free OpenCode enforcement plugin."""
from __future__ import annotations

import json
import sys


PLUGIN_VERSION = "1"


def plugin_source(python: str | None = None) -> str:
    interpreter = json.dumps(python or sys.executable)
    return f'''// Generated by `custodian-opencode setup`; do not edit.
// custodian-opencode-guard-version: {PLUGIN_VERSION}
const PYTHON = {interpreter};
const MODULE = "custodian.opencode_guard.cli";

function stable(value) {{
  if (Array.isArray(value)) return "[" + value.map(stable).join(",") + "]";
  if (value && typeof value === "object") {{
    return "{{" + Object.keys(value).sort().map(k => JSON.stringify(k) + ":" + stable(value[k])).join(",") + "}}";
  }}
  return JSON.stringify(value);
}}

export const CustodianOpenCodeGuard = async ({{ directory, worktree }}) => {{
  const approvals = new Map();
  return {{
    "tool.execute.before": async (input, output) => {{
      const workspace = worktree || directory;
      const requester = `opencode:${{input.sessionID || "unknown"}}`;
      const key = stable({{ tool: input.tool, arguments: output.args, workspace, requester }});
      const proposal = {{
        tool: input.tool,
        arguments: output.args || {{}},
        workspace,
        requester,
        session_id: input.sessionID || requester,
        approval_id: approvals.get(key),
      }};
      let proc;
      try {{
        proc = Bun.spawn([PYTHON, "-m", MODULE, "evaluate"], {{
          stdin: new Blob([JSON.stringify(proposal)]), stdout: "pipe", stderr: "pipe",
          env: process.env,
        }});
      }} catch (_) {{
        throw new Error("Custodian unavailable; OpenCode tool execution denied");
      }}
      const stdout = await new Response(proc.stdout).text();
      const code = await proc.exited;
      let decision;
      try {{ decision = JSON.parse(stdout); }} catch (_) {{
        throw new Error("Custodian returned malformed data; OpenCode tool execution denied");
      }}
      if (code !== 0 || !decision || !["autonomous", "approved", "escalation_required", "denied"].includes(decision.verdict)) {{
        throw new Error("Custodian validation failed; OpenCode tool execution denied");
      }}
      if (decision.verdict === "autonomous" || decision.verdict === "approved") {{
        approvals.delete(key);
        return;
      }}
      if (decision.verdict === "escalation_required" && decision.approval_id) {{
        approvals.set(key, decision.approval_id);
        throw new Error(`Custodian approval required: ${{decision.reason}}\n${{decision.next_step || decision.approval_id}}`);
      }}
      approvals.delete(key);
      throw new Error(`Custodian denied this OpenCode action: ${{decision.reason || "policy denial"}}`);
    }},
  }};
}};
'''
